package org.qifu.core.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbSysProgExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public TbSysProgExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOidIsNull() {
			addCriterion("OID is null");
			return (Criteria) this;
		}

		public Criteria andOidIsNotNull() {
			addCriterion("OID is not null");
			return (Criteria) this;
		}

		public Criteria andOidEqualTo(String value) {
			addCriterion("OID =", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidNotEqualTo(String value) {
			addCriterion("OID <>", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidGreaterThan(String value) {
			addCriterion("OID >", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidGreaterThanOrEqualTo(String value) {
			addCriterion("OID >=", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidLessThan(String value) {
			addCriterion("OID <", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidLessThanOrEqualTo(String value) {
			addCriterion("OID <=", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidLike(String value) {
			addCriterion("OID like", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidNotLike(String value) {
			addCriterion("OID not like", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidIn(List<String> values) {
			addCriterion("OID in", values, "oid");
			return (Criteria) this;
		}

		public Criteria andOidNotIn(List<String> values) {
			addCriterion("OID not in", values, "oid");
			return (Criteria) this;
		}

		public Criteria andOidBetween(String value1, String value2) {
			addCriterion("OID between", value1, value2, "oid");
			return (Criteria) this;
		}

		public Criteria andOidNotBetween(String value1, String value2) {
			addCriterion("OID not between", value1, value2, "oid");
			return (Criteria) this;
		}

		public Criteria andProgIdIsNull() {
			addCriterion("PROG_ID is null");
			return (Criteria) this;
		}

		public Criteria andProgIdIsNotNull() {
			addCriterion("PROG_ID is not null");
			return (Criteria) this;
		}

		public Criteria andProgIdEqualTo(String value) {
			addCriterion("PROG_ID =", value, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdNotEqualTo(String value) {
			addCriterion("PROG_ID <>", value, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdGreaterThan(String value) {
			addCriterion("PROG_ID >", value, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdGreaterThanOrEqualTo(String value) {
			addCriterion("PROG_ID >=", value, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdLessThan(String value) {
			addCriterion("PROG_ID <", value, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdLessThanOrEqualTo(String value) {
			addCriterion("PROG_ID <=", value, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdLike(String value) {
			addCriterion("PROG_ID like", value, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdNotLike(String value) {
			addCriterion("PROG_ID not like", value, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdIn(List<String> values) {
			addCriterion("PROG_ID in", values, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdNotIn(List<String> values) {
			addCriterion("PROG_ID not in", values, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdBetween(String value1, String value2) {
			addCriterion("PROG_ID between", value1, value2, "progId");
			return (Criteria) this;
		}

		public Criteria andProgIdNotBetween(String value1, String value2) {
			addCriterion("PROG_ID not between", value1, value2, "progId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("URL is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("URL is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("URL =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("URL <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("URL >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("URL >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("URL <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("URL <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("URL like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("URL not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("URL in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("URL not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("URL between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("URL not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andEditModeIsNull() {
			addCriterion("EDIT_MODE is null");
			return (Criteria) this;
		}

		public Criteria andEditModeIsNotNull() {
			addCriterion("EDIT_MODE is not null");
			return (Criteria) this;
		}

		public Criteria andEditModeEqualTo(String value) {
			addCriterion("EDIT_MODE =", value, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeNotEqualTo(String value) {
			addCriterion("EDIT_MODE <>", value, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeGreaterThan(String value) {
			addCriterion("EDIT_MODE >", value, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeGreaterThanOrEqualTo(String value) {
			addCriterion("EDIT_MODE >=", value, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeLessThan(String value) {
			addCriterion("EDIT_MODE <", value, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeLessThanOrEqualTo(String value) {
			addCriterion("EDIT_MODE <=", value, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeLike(String value) {
			addCriterion("EDIT_MODE like", value, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeNotLike(String value) {
			addCriterion("EDIT_MODE not like", value, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeIn(List<String> values) {
			addCriterion("EDIT_MODE in", values, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeNotIn(List<String> values) {
			addCriterion("EDIT_MODE not in", values, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeBetween(String value1, String value2) {
			addCriterion("EDIT_MODE between", value1, value2, "editMode");
			return (Criteria) this;
		}

		public Criteria andEditModeNotBetween(String value1, String value2) {
			addCriterion("EDIT_MODE not between", value1, value2, "editMode");
			return (Criteria) this;
		}

		public Criteria andIsDialogIsNull() {
			addCriterion("IS_DIALOG is null");
			return (Criteria) this;
		}

		public Criteria andIsDialogIsNotNull() {
			addCriterion("IS_DIALOG is not null");
			return (Criteria) this;
		}

		public Criteria andIsDialogEqualTo(String value) {
			addCriterion("IS_DIALOG =", value, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogNotEqualTo(String value) {
			addCriterion("IS_DIALOG <>", value, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogGreaterThan(String value) {
			addCriterion("IS_DIALOG >", value, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogGreaterThanOrEqualTo(String value) {
			addCriterion("IS_DIALOG >=", value, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogLessThan(String value) {
			addCriterion("IS_DIALOG <", value, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogLessThanOrEqualTo(String value) {
			addCriterion("IS_DIALOG <=", value, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogLike(String value) {
			addCriterion("IS_DIALOG like", value, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogNotLike(String value) {
			addCriterion("IS_DIALOG not like", value, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogIn(List<String> values) {
			addCriterion("IS_DIALOG in", values, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogNotIn(List<String> values) {
			addCriterion("IS_DIALOG not in", values, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogBetween(String value1, String value2) {
			addCriterion("IS_DIALOG between", value1, value2, "isDialog");
			return (Criteria) this;
		}

		public Criteria andIsDialogNotBetween(String value1, String value2) {
			addCriterion("IS_DIALOG not between", value1, value2, "isDialog");
			return (Criteria) this;
		}

		public Criteria andDialogWIsNull() {
			addCriterion("DIALOG_W is null");
			return (Criteria) this;
		}

		public Criteria andDialogWIsNotNull() {
			addCriterion("DIALOG_W is not null");
			return (Criteria) this;
		}

		public Criteria andDialogWEqualTo(Integer value) {
			addCriterion("DIALOG_W =", value, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWNotEqualTo(Integer value) {
			addCriterion("DIALOG_W <>", value, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWGreaterThan(Integer value) {
			addCriterion("DIALOG_W >", value, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWGreaterThanOrEqualTo(Integer value) {
			addCriterion("DIALOG_W >=", value, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWLessThan(Integer value) {
			addCriterion("DIALOG_W <", value, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWLessThanOrEqualTo(Integer value) {
			addCriterion("DIALOG_W <=", value, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWIn(List<Integer> values) {
			addCriterion("DIALOG_W in", values, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWNotIn(List<Integer> values) {
			addCriterion("DIALOG_W not in", values, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWBetween(Integer value1, Integer value2) {
			addCriterion("DIALOG_W between", value1, value2, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogWNotBetween(Integer value1, Integer value2) {
			addCriterion("DIALOG_W not between", value1, value2, "dialogW");
			return (Criteria) this;
		}

		public Criteria andDialogHIsNull() {
			addCriterion("DIALOG_H is null");
			return (Criteria) this;
		}

		public Criteria andDialogHIsNotNull() {
			addCriterion("DIALOG_H is not null");
			return (Criteria) this;
		}

		public Criteria andDialogHEqualTo(Integer value) {
			addCriterion("DIALOG_H =", value, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHNotEqualTo(Integer value) {
			addCriterion("DIALOG_H <>", value, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHGreaterThan(Integer value) {
			addCriterion("DIALOG_H >", value, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHGreaterThanOrEqualTo(Integer value) {
			addCriterion("DIALOG_H >=", value, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHLessThan(Integer value) {
			addCriterion("DIALOG_H <", value, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHLessThanOrEqualTo(Integer value) {
			addCriterion("DIALOG_H <=", value, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHIn(List<Integer> values) {
			addCriterion("DIALOG_H in", values, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHNotIn(List<Integer> values) {
			addCriterion("DIALOG_H not in", values, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHBetween(Integer value1, Integer value2) {
			addCriterion("DIALOG_H between", value1, value2, "dialogH");
			return (Criteria) this;
		}

		public Criteria andDialogHNotBetween(Integer value1, Integer value2) {
			addCriterion("DIALOG_H not between", value1, value2, "dialogH");
			return (Criteria) this;
		}

		public Criteria andProgSystemIsNull() {
			addCriterion("PROG_SYSTEM is null");
			return (Criteria) this;
		}

		public Criteria andProgSystemIsNotNull() {
			addCriterion("PROG_SYSTEM is not null");
			return (Criteria) this;
		}

		public Criteria andProgSystemEqualTo(String value) {
			addCriterion("PROG_SYSTEM =", value, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemNotEqualTo(String value) {
			addCriterion("PROG_SYSTEM <>", value, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemGreaterThan(String value) {
			addCriterion("PROG_SYSTEM >", value, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemGreaterThanOrEqualTo(String value) {
			addCriterion("PROG_SYSTEM >=", value, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemLessThan(String value) {
			addCriterion("PROG_SYSTEM <", value, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemLessThanOrEqualTo(String value) {
			addCriterion("PROG_SYSTEM <=", value, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemLike(String value) {
			addCriterion("PROG_SYSTEM like", value, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemNotLike(String value) {
			addCriterion("PROG_SYSTEM not like", value, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemIn(List<String> values) {
			addCriterion("PROG_SYSTEM in", values, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemNotIn(List<String> values) {
			addCriterion("PROG_SYSTEM not in", values, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemBetween(String value1, String value2) {
			addCriterion("PROG_SYSTEM between", value1, value2, "progSystem");
			return (Criteria) this;
		}

		public Criteria andProgSystemNotBetween(String value1, String value2) {
			addCriterion("PROG_SYSTEM not between", value1, value2, "progSystem");
			return (Criteria) this;
		}

		public Criteria andItemTypeIsNull() {
			addCriterion("ITEM_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andItemTypeIsNotNull() {
			addCriterion("ITEM_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andItemTypeEqualTo(String value) {
			addCriterion("ITEM_TYPE =", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeNotEqualTo(String value) {
			addCriterion("ITEM_TYPE <>", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeGreaterThan(String value) {
			addCriterion("ITEM_TYPE >", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ITEM_TYPE >=", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeLessThan(String value) {
			addCriterion("ITEM_TYPE <", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeLessThanOrEqualTo(String value) {
			addCriterion("ITEM_TYPE <=", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeLike(String value) {
			addCriterion("ITEM_TYPE like", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeNotLike(String value) {
			addCriterion("ITEM_TYPE not like", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeIn(List<String> values) {
			addCriterion("ITEM_TYPE in", values, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeNotIn(List<String> values) {
			addCriterion("ITEM_TYPE not in", values, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeBetween(String value1, String value2) {
			addCriterion("ITEM_TYPE between", value1, value2, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeNotBetween(String value1, String value2) {
			addCriterion("ITEM_TYPE not between", value1, value2, "itemType");
			return (Criteria) this;
		}

		public Criteria andIconIsNull() {
			addCriterion("ICON is null");
			return (Criteria) this;
		}

		public Criteria andIconIsNotNull() {
			addCriterion("ICON is not null");
			return (Criteria) this;
		}

		public Criteria andIconEqualTo(String value) {
			addCriterion("ICON =", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotEqualTo(String value) {
			addCriterion("ICON <>", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconGreaterThan(String value) {
			addCriterion("ICON >", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconGreaterThanOrEqualTo(String value) {
			addCriterion("ICON >=", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLessThan(String value) {
			addCriterion("ICON <", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLessThanOrEqualTo(String value) {
			addCriterion("ICON <=", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLike(String value) {
			addCriterion("ICON like", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotLike(String value) {
			addCriterion("ICON not like", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconIn(List<String> values) {
			addCriterion("ICON in", values, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotIn(List<String> values) {
			addCriterion("ICON not in", values, "icon");
			return (Criteria) this;
		}

		public Criteria andIconBetween(String value1, String value2) {
			addCriterion("ICON between", value1, value2, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotBetween(String value1, String value2) {
			addCriterion("ICON not between", value1, value2, "icon");
			return (Criteria) this;
		}

		public Criteria andCuseridIsNull() {
			addCriterion("CUSERID is null");
			return (Criteria) this;
		}

		public Criteria andCuseridIsNotNull() {
			addCriterion("CUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andCuseridEqualTo(String value) {
			addCriterion("CUSERID =", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridNotEqualTo(String value) {
			addCriterion("CUSERID <>", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridGreaterThan(String value) {
			addCriterion("CUSERID >", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridGreaterThanOrEqualTo(String value) {
			addCriterion("CUSERID >=", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridLessThan(String value) {
			addCriterion("CUSERID <", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridLessThanOrEqualTo(String value) {
			addCriterion("CUSERID <=", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridLike(String value) {
			addCriterion("CUSERID like", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridNotLike(String value) {
			addCriterion("CUSERID not like", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridIn(List<String> values) {
			addCriterion("CUSERID in", values, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridNotIn(List<String> values) {
			addCriterion("CUSERID not in", values, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridBetween(String value1, String value2) {
			addCriterion("CUSERID between", value1, value2, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridNotBetween(String value1, String value2) {
			addCriterion("CUSERID not between", value1, value2, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCdateIsNull() {
			addCriterion("CDATE is null");
			return (Criteria) this;
		}

		public Criteria andCdateIsNotNull() {
			addCriterion("CDATE is not null");
			return (Criteria) this;
		}

		public Criteria andCdateEqualTo(Date value) {
			addCriterion("CDATE =", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotEqualTo(Date value) {
			addCriterion("CDATE <>", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateGreaterThan(Date value) {
			addCriterion("CDATE >", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateGreaterThanOrEqualTo(Date value) {
			addCriterion("CDATE >=", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateLessThan(Date value) {
			addCriterion("CDATE <", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateLessThanOrEqualTo(Date value) {
			addCriterion("CDATE <=", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateIn(List<Date> values) {
			addCriterion("CDATE in", values, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotIn(List<Date> values) {
			addCriterion("CDATE not in", values, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateBetween(Date value1, Date value2) {
			addCriterion("CDATE between", value1, value2, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotBetween(Date value1, Date value2) {
			addCriterion("CDATE not between", value1, value2, "cdate");
			return (Criteria) this;
		}

		public Criteria andUuseridIsNull() {
			addCriterion("UUSERID is null");
			return (Criteria) this;
		}

		public Criteria andUuseridIsNotNull() {
			addCriterion("UUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andUuseridEqualTo(String value) {
			addCriterion("UUSERID =", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridNotEqualTo(String value) {
			addCriterion("UUSERID <>", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridGreaterThan(String value) {
			addCriterion("UUSERID >", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridGreaterThanOrEqualTo(String value) {
			addCriterion("UUSERID >=", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridLessThan(String value) {
			addCriterion("UUSERID <", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridLessThanOrEqualTo(String value) {
			addCriterion("UUSERID <=", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridLike(String value) {
			addCriterion("UUSERID like", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridNotLike(String value) {
			addCriterion("UUSERID not like", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridIn(List<String> values) {
			addCriterion("UUSERID in", values, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridNotIn(List<String> values) {
			addCriterion("UUSERID not in", values, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridBetween(String value1, String value2) {
			addCriterion("UUSERID between", value1, value2, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridNotBetween(String value1, String value2) {
			addCriterion("UUSERID not between", value1, value2, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUdateIsNull() {
			addCriterion("UDATE is null");
			return (Criteria) this;
		}

		public Criteria andUdateIsNotNull() {
			addCriterion("UDATE is not null");
			return (Criteria) this;
		}

		public Criteria andUdateEqualTo(Date value) {
			addCriterion("UDATE =", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateNotEqualTo(Date value) {
			addCriterion("UDATE <>", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateGreaterThan(Date value) {
			addCriterion("UDATE >", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateGreaterThanOrEqualTo(Date value) {
			addCriterion("UDATE >=", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateLessThan(Date value) {
			addCriterion("UDATE <", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateLessThanOrEqualTo(Date value) {
			addCriterion("UDATE <=", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateIn(List<Date> values) {
			addCriterion("UDATE in", values, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateNotIn(List<Date> values) {
			addCriterion("UDATE not in", values, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateBetween(Date value1, Date value2) {
			addCriterion("UDATE between", value1, value2, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateNotBetween(Date value1, Date value2) {
			addCriterion("UDATE not between", value1, value2, "udate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_sys_prog
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 02 15:46:56 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}