package org.qifu.core.entity;

import java.util.Date;

public class TbSys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.OID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.SYS_ID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String sysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.NAME
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.HOST
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.CONTEXT_PATH
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String contextPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.IS_LOCAL
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String isLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.ICON
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.CUSERID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String cuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.CDATE
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.UUSERID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private String uuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys.UDATE
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    private Date udate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.OID
     *
     * @return the value of tb_sys.OID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.OID
     *
     * @param oid the value for tb_sys.OID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.SYS_ID
     *
     * @return the value of tb_sys.SYS_ID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.SYS_ID
     *
     * @param sysId the value for tb_sys.SYS_ID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.NAME
     *
     * @return the value of tb_sys.NAME
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.NAME
     *
     * @param name the value for tb_sys.NAME
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.HOST
     *
     * @return the value of tb_sys.HOST
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.HOST
     *
     * @param host the value for tb_sys.HOST
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.CONTEXT_PATH
     *
     * @return the value of tb_sys.CONTEXT_PATH
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getContextPath() {
        return contextPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.CONTEXT_PATH
     *
     * @param contextPath the value for tb_sys.CONTEXT_PATH
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setContextPath(String contextPath) {
        this.contextPath = contextPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.IS_LOCAL
     *
     * @return the value of tb_sys.IS_LOCAL
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getIsLocal() {
        return isLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.IS_LOCAL
     *
     * @param isLocal the value for tb_sys.IS_LOCAL
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setIsLocal(String isLocal) {
        this.isLocal = isLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.ICON
     *
     * @return the value of tb_sys.ICON
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.ICON
     *
     * @param icon the value for tb_sys.ICON
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.CUSERID
     *
     * @return the value of tb_sys.CUSERID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getCuserid() {
        return cuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.CUSERID
     *
     * @param cuserid the value for tb_sys.CUSERID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setCuserid(String cuserid) {
        this.cuserid = cuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.CDATE
     *
     * @return the value of tb_sys.CDATE
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.CDATE
     *
     * @param cdate the value for tb_sys.CDATE
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.UUSERID
     *
     * @return the value of tb_sys.UUSERID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public String getUuserid() {
        return uuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.UUSERID
     *
     * @param uuserid the value for tb_sys.UUSERID
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setUuserid(String uuserid) {
        this.uuserid = uuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys.UDATE
     *
     * @return the value of tb_sys.UDATE
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public Date getUdate() {
        return udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys.UDATE
     *
     * @param udate the value for tb_sys.UDATE
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    public void setUdate(Date udate) {
        this.udate = udate;
    }
}