package org.qifu.core.entity;

import java.util.Date;

public class TbSysProg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.OID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String oid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.PROG_ID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String progId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.NAME
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.URL
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.EDIT_MODE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String editMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.IS_DIALOG
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String isDialog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.DIALOG_W
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private Integer dialogW;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.DIALOG_H
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private Integer dialogH;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.PROG_SYSTEM
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String progSystem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.ITEM_TYPE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String itemType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.ICON
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.CUSERID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String cuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.CDATE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private Date cdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.UUSERID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private String uuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_prog.UDATE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	private Date udate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.OID
	 * @return  the value of tb_sys_prog.OID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.OID
	 * @param oid  the value for tb_sys_prog.OID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setOid(String oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.PROG_ID
	 * @return  the value of tb_sys_prog.PROG_ID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getProgId() {
		return progId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.PROG_ID
	 * @param progId  the value for tb_sys_prog.PROG_ID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setProgId(String progId) {
		this.progId = progId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.NAME
	 * @return  the value of tb_sys_prog.NAME
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.NAME
	 * @param name  the value for tb_sys_prog.NAME
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.URL
	 * @return  the value of tb_sys_prog.URL
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.URL
	 * @param url  the value for tb_sys_prog.URL
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.EDIT_MODE
	 * @return  the value of tb_sys_prog.EDIT_MODE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getEditMode() {
		return editMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.EDIT_MODE
	 * @param editMode  the value for tb_sys_prog.EDIT_MODE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setEditMode(String editMode) {
		this.editMode = editMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.IS_DIALOG
	 * @return  the value of tb_sys_prog.IS_DIALOG
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getIsDialog() {
		return isDialog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.IS_DIALOG
	 * @param isDialog  the value for tb_sys_prog.IS_DIALOG
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setIsDialog(String isDialog) {
		this.isDialog = isDialog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.DIALOG_W
	 * @return  the value of tb_sys_prog.DIALOG_W
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public Integer getDialogW() {
		return dialogW;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.DIALOG_W
	 * @param dialogW  the value for tb_sys_prog.DIALOG_W
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setDialogW(Integer dialogW) {
		this.dialogW = dialogW;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.DIALOG_H
	 * @return  the value of tb_sys_prog.DIALOG_H
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public Integer getDialogH() {
		return dialogH;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.DIALOG_H
	 * @param dialogH  the value for tb_sys_prog.DIALOG_H
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setDialogH(Integer dialogH) {
		this.dialogH = dialogH;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.PROG_SYSTEM
	 * @return  the value of tb_sys_prog.PROG_SYSTEM
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getProgSystem() {
		return progSystem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.PROG_SYSTEM
	 * @param progSystem  the value for tb_sys_prog.PROG_SYSTEM
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setProgSystem(String progSystem) {
		this.progSystem = progSystem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.ITEM_TYPE
	 * @return  the value of tb_sys_prog.ITEM_TYPE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getItemType() {
		return itemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.ITEM_TYPE
	 * @param itemType  the value for tb_sys_prog.ITEM_TYPE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.ICON
	 * @return  the value of tb_sys_prog.ICON
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.ICON
	 * @param icon  the value for tb_sys_prog.ICON
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.CUSERID
	 * @return  the value of tb_sys_prog.CUSERID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getCuserid() {
		return cuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.CUSERID
	 * @param cuserid  the value for tb_sys_prog.CUSERID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setCuserid(String cuserid) {
		this.cuserid = cuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.CDATE
	 * @return  the value of tb_sys_prog.CDATE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public Date getCdate() {
		return cdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.CDATE
	 * @param cdate  the value for tb_sys_prog.CDATE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.UUSERID
	 * @return  the value of tb_sys_prog.UUSERID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public String getUuserid() {
		return uuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.UUSERID
	 * @param uuserid  the value for tb_sys_prog.UUSERID
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setUuserid(String uuserid) {
		this.uuserid = uuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_prog.UDATE
	 * @return  the value of tb_sys_prog.UDATE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public Date getUdate() {
		return udate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_prog.UDATE
	 * @param udate  the value for tb_sys_prog.UDATE
	 * @mbg.generated  Tue Jun 02 15:35:17 CST 2020
	 */
	public void setUdate(Date udate) {
		this.udate = udate;
	}
}