package org.qifu.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.qifu.core.mapper.TbAccount;
import org.qifu.core.mapper.TbAccountExample;
import org.qifu.core.mapper.TbAccountKey;

public interface TbAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	long countByExample(TbAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	int deleteByExample(TbAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	int deleteByPrimaryKey(TbAccountKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	int insert(TbAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	int insertSelective(TbAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	List<TbAccount> selectByExample(TbAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	TbAccount selectByPrimaryKey(TbAccountKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	int updateByExampleSelective(@Param("record") TbAccount record, @Param("example") TbAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	int updateByExample(@Param("record") TbAccount record, @Param("example") TbAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	int updateByPrimaryKeySelective(TbAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	int updateByPrimaryKey(TbAccount record);
}