package org.qifu.core.mapper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbAccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public TbAccountExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOidIsNull() {
			addCriterion("OID is null");
			return (Criteria) this;
		}

		public Criteria andOidIsNotNull() {
			addCriterion("OID is not null");
			return (Criteria) this;
		}

		public Criteria andOidEqualTo(String value) {
			addCriterion("OID =", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidNotEqualTo(String value) {
			addCriterion("OID <>", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidGreaterThan(String value) {
			addCriterion("OID >", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidGreaterThanOrEqualTo(String value) {
			addCriterion("OID >=", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidLessThan(String value) {
			addCriterion("OID <", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidLessThanOrEqualTo(String value) {
			addCriterion("OID <=", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidLike(String value) {
			addCriterion("OID like", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidNotLike(String value) {
			addCriterion("OID not like", value, "oid");
			return (Criteria) this;
		}

		public Criteria andOidIn(List<String> values) {
			addCriterion("OID in", values, "oid");
			return (Criteria) this;
		}

		public Criteria andOidNotIn(List<String> values) {
			addCriterion("OID not in", values, "oid");
			return (Criteria) this;
		}

		public Criteria andOidBetween(String value1, String value2) {
			addCriterion("OID between", value1, value2, "oid");
			return (Criteria) this;
		}

		public Criteria andOidNotBetween(String value1, String value2) {
			addCriterion("OID not between", value1, value2, "oid");
			return (Criteria) this;
		}

		public Criteria andAccountIsNull() {
			addCriterion("ACCOUNT is null");
			return (Criteria) this;
		}

		public Criteria andAccountIsNotNull() {
			addCriterion("ACCOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andAccountEqualTo(String value) {
			addCriterion("ACCOUNT =", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotEqualTo(String value) {
			addCriterion("ACCOUNT <>", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountGreaterThan(String value) {
			addCriterion("ACCOUNT >", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNT >=", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLessThan(String value) {
			addCriterion("ACCOUNT <", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNT <=", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLike(String value) {
			addCriterion("ACCOUNT like", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotLike(String value) {
			addCriterion("ACCOUNT not like", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountIn(List<String> values) {
			addCriterion("ACCOUNT in", values, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotIn(List<String> values) {
			addCriterion("ACCOUNT not in", values, "account");
			return (Criteria) this;
		}

		public Criteria andAccountBetween(String value1, String value2) {
			addCriterion("ACCOUNT between", value1, value2, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotBetween(String value1, String value2) {
			addCriterion("ACCOUNT not between", value1, value2, "account");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andOnJobIsNull() {
			addCriterion("ON_JOB is null");
			return (Criteria) this;
		}

		public Criteria andOnJobIsNotNull() {
			addCriterion("ON_JOB is not null");
			return (Criteria) this;
		}

		public Criteria andOnJobEqualTo(String value) {
			addCriterion("ON_JOB =", value, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobNotEqualTo(String value) {
			addCriterion("ON_JOB <>", value, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobGreaterThan(String value) {
			addCriterion("ON_JOB >", value, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobGreaterThanOrEqualTo(String value) {
			addCriterion("ON_JOB >=", value, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobLessThan(String value) {
			addCriterion("ON_JOB <", value, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobLessThanOrEqualTo(String value) {
			addCriterion("ON_JOB <=", value, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobLike(String value) {
			addCriterion("ON_JOB like", value, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobNotLike(String value) {
			addCriterion("ON_JOB not like", value, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobIn(List<String> values) {
			addCriterion("ON_JOB in", values, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobNotIn(List<String> values) {
			addCriterion("ON_JOB not in", values, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobBetween(String value1, String value2) {
			addCriterion("ON_JOB between", value1, value2, "onJob");
			return (Criteria) this;
		}

		public Criteria andOnJobNotBetween(String value1, String value2) {
			addCriterion("ON_JOB not between", value1, value2, "onJob");
			return (Criteria) this;
		}

		public Criteria andCuseridIsNull() {
			addCriterion("CUSERID is null");
			return (Criteria) this;
		}

		public Criteria andCuseridIsNotNull() {
			addCriterion("CUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andCuseridEqualTo(String value) {
			addCriterion("CUSERID =", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridNotEqualTo(String value) {
			addCriterion("CUSERID <>", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridGreaterThan(String value) {
			addCriterion("CUSERID >", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridGreaterThanOrEqualTo(String value) {
			addCriterion("CUSERID >=", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridLessThan(String value) {
			addCriterion("CUSERID <", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridLessThanOrEqualTo(String value) {
			addCriterion("CUSERID <=", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridLike(String value) {
			addCriterion("CUSERID like", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridNotLike(String value) {
			addCriterion("CUSERID not like", value, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridIn(List<String> values) {
			addCriterion("CUSERID in", values, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridNotIn(List<String> values) {
			addCriterion("CUSERID not in", values, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridBetween(String value1, String value2) {
			addCriterion("CUSERID between", value1, value2, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCuseridNotBetween(String value1, String value2) {
			addCriterion("CUSERID not between", value1, value2, "cuserid");
			return (Criteria) this;
		}

		public Criteria andCdateIsNull() {
			addCriterion("CDATE is null");
			return (Criteria) this;
		}

		public Criteria andCdateIsNotNull() {
			addCriterion("CDATE is not null");
			return (Criteria) this;
		}

		public Criteria andCdateEqualTo(Date value) {
			addCriterion("CDATE =", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotEqualTo(Date value) {
			addCriterion("CDATE <>", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateGreaterThan(Date value) {
			addCriterion("CDATE >", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateGreaterThanOrEqualTo(Date value) {
			addCriterion("CDATE >=", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateLessThan(Date value) {
			addCriterion("CDATE <", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateLessThanOrEqualTo(Date value) {
			addCriterion("CDATE <=", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateIn(List<Date> values) {
			addCriterion("CDATE in", values, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotIn(List<Date> values) {
			addCriterion("CDATE not in", values, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateBetween(Date value1, Date value2) {
			addCriterion("CDATE between", value1, value2, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotBetween(Date value1, Date value2) {
			addCriterion("CDATE not between", value1, value2, "cdate");
			return (Criteria) this;
		}

		public Criteria andUuseridIsNull() {
			addCriterion("UUSERID is null");
			return (Criteria) this;
		}

		public Criteria andUuseridIsNotNull() {
			addCriterion("UUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andUuseridEqualTo(String value) {
			addCriterion("UUSERID =", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridNotEqualTo(String value) {
			addCriterion("UUSERID <>", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridGreaterThan(String value) {
			addCriterion("UUSERID >", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridGreaterThanOrEqualTo(String value) {
			addCriterion("UUSERID >=", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridLessThan(String value) {
			addCriterion("UUSERID <", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridLessThanOrEqualTo(String value) {
			addCriterion("UUSERID <=", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridLike(String value) {
			addCriterion("UUSERID like", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridNotLike(String value) {
			addCriterion("UUSERID not like", value, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridIn(List<String> values) {
			addCriterion("UUSERID in", values, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridNotIn(List<String> values) {
			addCriterion("UUSERID not in", values, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridBetween(String value1, String value2) {
			addCriterion("UUSERID between", value1, value2, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUuseridNotBetween(String value1, String value2) {
			addCriterion("UUSERID not between", value1, value2, "uuserid");
			return (Criteria) this;
		}

		public Criteria andUdateIsNull() {
			addCriterion("UDATE is null");
			return (Criteria) this;
		}

		public Criteria andUdateIsNotNull() {
			addCriterion("UDATE is not null");
			return (Criteria) this;
		}

		public Criteria andUdateEqualTo(Date value) {
			addCriterion("UDATE =", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateNotEqualTo(Date value) {
			addCriterion("UDATE <>", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateGreaterThan(Date value) {
			addCriterion("UDATE >", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateGreaterThanOrEqualTo(Date value) {
			addCriterion("UDATE >=", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateLessThan(Date value) {
			addCriterion("UDATE <", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateLessThanOrEqualTo(Date value) {
			addCriterion("UDATE <=", value, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateIn(List<Date> values) {
			addCriterion("UDATE in", values, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateNotIn(List<Date> values) {
			addCriterion("UDATE not in", values, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateBetween(Date value1, Date value2) {
			addCriterion("UDATE between", value1, value2, "udate");
			return (Criteria) this;
		}

		public Criteria andUdateNotBetween(Date value1, Date value2) {
			addCriterion("UDATE not between", value1, value2, "udate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_account
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_account
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 15 10:49:15 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}