package org.qifu.core.mapper;

import java.util.Date;

public class TbAccount extends TbAccountKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_account.PASSWORD
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_account.ON_JOB
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	private String onJob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_account.CUSERID
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	private String cuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_account.CDATE
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	private Date cdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_account.UUSERID
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	private String uuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_account.UDATE
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	private Date udate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_account.PASSWORD
	 * @return  the value of tb_account.PASSWORD
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_account.PASSWORD
	 * @param password  the value for tb_account.PASSWORD
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_account.ON_JOB
	 * @return  the value of tb_account.ON_JOB
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public String getOnJob() {
		return onJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_account.ON_JOB
	 * @param onJob  the value for tb_account.ON_JOB
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void setOnJob(String onJob) {
		this.onJob = onJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_account.CUSERID
	 * @return  the value of tb_account.CUSERID
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public String getCuserid() {
		return cuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_account.CUSERID
	 * @param cuserid  the value for tb_account.CUSERID
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void setCuserid(String cuserid) {
		this.cuserid = cuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_account.CDATE
	 * @return  the value of tb_account.CDATE
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public Date getCdate() {
		return cdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_account.CDATE
	 * @param cdate  the value for tb_account.CDATE
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_account.UUSERID
	 * @return  the value of tb_account.UUSERID
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public String getUuserid() {
		return uuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_account.UUSERID
	 * @param uuserid  the value for tb_account.UUSERID
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void setUuserid(String uuserid) {
		this.uuserid = uuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_account.UDATE
	 * @return  the value of tb_account.UDATE
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public Date getUdate() {
		return udate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_account.UDATE
	 * @param udate  the value for tb_account.UDATE
	 * @mbg.generated  Wed Apr 15 10:49:15 CST 2020
	 */
	public void setUdate(Date udate) {
		this.udate = udate;
	}
}