package org.qifu.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.qifu.core.entity.TbSysProg;
import org.qifu.core.entity.TbSysProgExample;

public interface TbSysProgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	long countByExample(TbSysProgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	int deleteByExample(TbSysProgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	int deleteByPrimaryKey(String oid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	int insert(TbSysProg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	int insertSelective(TbSysProg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	List<TbSysProg> selectByExample(TbSysProgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	TbSysProg selectByPrimaryKey(String oid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	int updateByExampleSelective(@Param("record") TbSysProg record, @Param("example") TbSysProgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	int updateByExample(@Param("record") TbSysProg record, @Param("example") TbSysProgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	int updateByPrimaryKeySelective(TbSysProg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_prog
	 * @mbg.generated  Tue Jun 02 15:46:56 CST 2020
	 */
	int updateByPrimaryKey(TbSysProg record);
}