package org.qifu.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.qifu.core.entity.TbSys;
import org.qifu.core.entity.TbSysExample;

public interface TbSysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    long countByExample(TbSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    int deleteByExample(TbSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    int insert(TbSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    int insertSelective(TbSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    List<TbSys> selectByExample(TbSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    TbSys selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbSys record, @Param("example") TbSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    int updateByExample(@Param("record") TbSys record, @Param("example") TbSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    int updateByPrimaryKeySelective(TbSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys
     *
     * @mbg.generated Fri Jul 17 23:42:02 CST 2020
     */
    int updateByPrimaryKey(TbSys record);
}